name: Pull Request Checks

on:
  pull_request:
    branches:
      - main  # Or whatever your main development branch is

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!